/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-02-17 03:03:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class js1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\r\n");
      out.write("function idCheck() {\r\n");
      out.write("	// id에 입력한 값을 가져고 와서\r\n");
      out.write("	// 글자수가 5 미만이면 다시 작성하세요. 메시지 프린트\r\n");
      out.write("	// 미리 객체를 생성해 놨음 ==> 내장된 객체\r\n");
      out.write("	// window: 브라우저 전체\r\n");
      out.write("	// document: body태그 부분\r\n");
      out.write("	// console: 개발할 때 확인하는 창\r\n");
      out.write("	// location: 주소부분, location.href =\"\"\r\n");
      out.write("	idValue = document.getElementById(\"id\").value; // <input name=\"id\" id=\"id\" value=\"test\">\r\n");
      out.write("	text = \"\";\r\n");
      out.write("	if(idValue.length < 5) {\r\n");
      out.write("		console.log(\"5미만 입니다. 다시 입력해주세요\");\r\n");
      out.write("		text = \"5미만 입니다. 다시 입력해주세요\"\r\n");
      out.write("		document.getElementById(\"id\").value = \"\";\r\n");
      out.write("	}\r\n");
      out.write("	else {\r\n");
      out.write("		console.log(\"5이상 입니다.\");\r\n");
      out.write("		text = \"5이상 입니다. 확인완료\";\r\n");
      out.write("	}\r\n");
      out.write("	document.getElementById(\"result\").innerHTML = text;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function pwCheck() {\r\n");
      out.write("	pw1Value = document.getElementById(\"pw1\").value;\r\n");
      out.write("	pw2Value = document.getElementById(\"pw2\").value;\r\n");
      out.write("	text = \"\";\r\n");
      out.write("	if(pw1Value == pw2Value) {\r\n");
      out.write("		console.log(\"일치\");\r\n");
      out.write("		text = \"<span style='color:blue;'>일치\"\r\n");
      out.write("		+ \"<img src='resources/img/ok.jpg'> </span>\"\r\n");
      out.write("	}\r\n");
      out.write("	else {\r\n");
      out.write("		console.log(\"불일치\");\r\n");
      out.write("		document.getElementById(\"pw1\").value = \"\";\r\n");
      out.write("		document.getElementById(\"pw2\").value = \"\";\r\n");
      out.write("		text = \"<span style='color:red;'>불일치\"\r\n");
      out.write("			+ \"<img src='resources/img/no.jpg' width='200px' height='200px'> </span>\"\r\n");
      out.write("	}\r\n");
      out.write("	document.getElementById(\"result\").innerHTML = text;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h3>자바 스크립트 테스트</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("아이디 : <input name=\"id\" id=\"id\" value=\"test\">\r\n");
      out.write("<button onclick=\"idCheck()\">글자수 체크</button><br>\r\n");
      out.write("패스워드 : <input name=\"pw1\" id=\"pw1\" value=\"1234\"><br>\r\n");
      out.write("패스워드2 : <input name=\"pw2\" id=\"pw2\" value=\"1234\">\r\n");
      out.write("<button onclick=\"pwCheck()\">패스워드 동일</button>\r\n");
      out.write("<hr>\r\n");
      out.write("<div id=\"result\">\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
